apiVersion: v1
kind: Service
metadata:
  name: fruit
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: fruit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fruit
  template:
    metadata:
      labels:
        app: fruit
    spec:
      containers:
        - name: fruit
          image: serrodcal/quarkus-fruit-performance:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: vertx-reactive:postgresql://database:5432/quarkus_test
          resources:
            requests:
              memory: 300M
              cpu: 1000m
            limits:
              memory: 300M
              cpu: 1000m